### ISSUE TITLE
Please give 'barry' co-ownership on PyPI project

### ISSUE THREAD

**Issue by warsaw** [paulproteus/dirtbike#14]
This is actually a blocker for 0.2 (unless you want to do the upload Asheesh, but I am very happy to do it).  

https://pypi.python.org/pypi/dirtbike/0.1

I am ready for the 0.2 release.  I'm using it now in a local staging environment to build the full pip stack and it's working very nicely.  I want to do a tarball release on PyPI, and then upload the first version to Debian NEW.

My PyPI user is 'barry'.

**Comment by paulproteus** [comment]
OK, cool.​

**Comment by warsaw** [comment]
Thanks!
