### ISSUE TITLE
Use setuptools.setup

### ISSUE THREAD

**Issue by warsaw** [paulproteus/dirtbike#2]
In order to get the entry_points to work, we need setuptool's setup() not distutils.core.  PR coming momentarily.

**Comment by paulproteus** [comment]
Fascinating. Thanks!

**Comment by paulproteus** [comment]
I wonder why they were working on my laptop. Probably because I have `setuptools` installed globally...??!?

**Comment by dstufft** [comment]
If you use pip to install something we do bad things to force everything to use setuptools.

**Comment by paulproteus** [comment]
Oh, right, of course. I totally knew that!​
